apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dpoint-checkin-api
  name: dpoint-checkin-api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpoint-checkin-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dpoint-checkin-api
    spec:
      containers:
        - image: #{ImageTag}#
          imagePullPolicy: IfNotPresent

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: #{NetCoreEnvironment}#

          name: dpoint-checkin-api-container-development
